name: auto-merge-readme

on:
  pull_request:
    branches: [ main ]
    types: [ opened ]

permissions:
  pull-requests: write
  contents: write

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    if: >-
      startsWith(github.head_ref, 'auto/')
      && github.event.pull_request.user.login == 'bufferings'
    env:
      PR_URL: ${{github.event.pull_request.html_url}}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Approve PR
        run: gh pr review "$PR_URL" --approve

      - name: Enable auto-merge
        run: gh pr merge --merge --auto "$PR_URL"
