name: auto-merge-pr

on:
  pull_request:
    branches:
      - main

permissions:
  pull-requests: write
  contents: write

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "github.head_ref=${{ github.head_ref }}"
          echo "github.actor=${{ github.actor }}"
          echo "github.event.pull_request.html_url=${{ github.event.pull_request.html_url }}"
          echo "github.event.pull_request.user.login=${{ github.event.pull_request.user.login }}"

  auto-merge:
    runs-on: ubuntu-latest
    if: >
      startsWith(github.head_ref, 'update/')
      && github.actor == 'my-dependabot'
    env:
      PR_URL: ${{github.event.pull_request.html_url}}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Approve PR
        run: gh pr review "$PR_URL" --approve

      - name: Enable auto-merge
        run: gh pr merge --merge --auto "$PR_URL"
