name: auto-merge-readme

on:
  pull_request:
    branches: [ main ]
    types: [ opened, synchronize ]

permissions:
  pull-requests: write
  contents: write

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    if: >-
      startsWith(github.head_ref, 'auto/')
      && github.event.pull_request.user.login == 'bufferings'
    env:
      PR_URL: ${{github.event.pull_request.html_url}}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout repository with preceding commits
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Check if only README.md is updated
        env:
          BASE_REF: ${{ github.base_ref }}
        run: |
          echo "BASE_REF=$BASE_REF"
          git diff --name-only "origin/$BASE_REF" HEAD | tee /tmp/diffs
          cat /tmp/diffs


      # - name: Approve PR
      #   run: gh pr review "$PR_URL" --approve

      # - name: Enable auto-merge
      #   run: gh pr merge --merge --auto "$PR_URL"
